function [L, numLabels] = sbsuperpixel(I, N, compactness, numIterations, ...
    method)
arguments(Input)
    I (:,:,:) {mustBeNumericOrLogical};
    N {mustBePositive, mustBeInteger, mustBeReal, mustBeScalarOrEmpty, ...
        mustBeNonempty} = 15;
    compactness {mustBeNonnegative, mustBeNumeric, mustBeScalarOrEmpty, ...
        mustBeNonempty} = 8; % Default: 10 (typical range: [1 20])
    numIterations {mustBePositive, mustBeInteger, mustBeReal, mustBeScalarOrEmpty, ...
        mustBeNonempty} = 10;
    method {mustBeMember(method, {'slic0', 'slic'})} = 'slic0';
end
[L, numLabels] = superpixels(I, N, ...
    "Compactness", compactness, ...
    "Method", method, ...
    "NumIterations", numIterations ...
    );
end