function changeFrameRate(app, newSPF)
fprintf('[changeFrameRate] [%0.4g %0.4g]\n', newSPF);
usingTimer = ~get(app.vobj,'FramesAcquiredFcnCount');
num = newSPF(1); den = newSPF(2);
if (num==1) && (den > 15) %((den==1) || (den > 15))
    fprintf('[changeFrameRate] Not using timer.\n');
    useTimer = false;
    % Max timer interval: 2147483647
    args = {'FrameGrabInterval', den, ...
        'FramesAcquiredFcnCount', 1, ...
        'FramesPerTrigger', Inf, ...
        'TriggerRepeat', 0, ...
        'TimerFcn', [], ...
        'FramesAcquiredFcn', { @sbsense.SBSenseApp.getImageData, ...
        app.liveimg }, ...
        'TriggerFcn', @(~,e) fprintf('Trigger (e.Type: %s). e.Data:\n%s\n', e.Type, formattedDisplayText(e.Data)), ... % Or a failsafe trigger fcn?
        ... %'TriggerFcn', { @sbsense.SBSenseApp.getImageData, ...
        ... %app.liveimg } ...
        };
    trigtype = "immediate";
else
    fprintf('[changeFrameRate] Using timer.\n');
    % newSPF = num / den;
    useTimer = true;
    args = {'FrameGrabInterval', 1, ...
        'FramesAcquiredFcnCount', 0, ... % so FAFcn doesn't matter
        'FramesPerTrigger', 1, ...
        'TriggerRepeat', Inf, ...
        'TimerFcn', @sbsense.SBSenseApp.onVideoTimerTick, ...
        'FramesAcquiredFcn', [], ...
        'TriggerFcn', { @sbsense.SBSenseApp.getImageData, ...
        app.liveimg }, ...
        'TimerPeriod', num/den, ...
        };
    trigtype = "manual";
end
app.PreviewFramerate = single([num den]);
mustRestart = isrunning(app.vobj) && (usingTimer ~= useTimer);
fprintf('[changeFramerate] isrunning: %d, usingTimer: %d, useTimer: %d, mustRestart: %d\n', ...
    isrunning(app.vobj), usingTimer, useTimer, mustRestart);
if mustRestart
    stop(app.vobj);
    wait(app.vobj, 10, "running"); % TODO: Timeout / ask to continue waiting
    wait(app.vobj, 10, "logging");
    triggerconfig(app.vobj, trigtype);
end
set(app.vobj, args{:});
if mustRestart
    fprintf('[changeFrameRate] Starting vobj.\n');
    start(app.vobj);
    if useTimer
        fprintf('[changeFrameRate] trigger\n');
        trigger(app.vobj);
    end
end
%if (nargin==2) || varargin{3}

%end
end