function quickExport_ChannelIPs(app, varargin)
    [file,path,~] = uiputfile( ...
        { '*.xls', 'MS Excel Spreadsheet file' }, ...
        'Select export location and filename for primary data', ...
        '');
    if ~file
        return;
    end
    %if idx==1
        suff = '.xls';
    %else
    %    suff = '.csv';
    %end

    if(~endsWith(file, suff))
        file = sprintf('%s%s', file, suff);
    end
    fullpath = fullfile(path, file);

    relTimes = app.DataTable{1}.RelTime;
    absTimes = relTimes + app.TimeZero;
    absDates = string(absTimes, 'yyyy/MM/dd');
    absTimes = string(absTimes, 'HH:mm:ss.SSSSSS');
    relTimes = string(relTimes, 'mm:ss.SSSSSS');
    indexColumns = rows2vars(table(absDates,absTimes, ...
        relTimes, app.DataTable{1}.Index)); %, ...
        %'VariableNames', {'Abs Date', 'Abs Time', 'Rel Time', 'Datapt Idx'});
    
    %ipColumns = table(app.ChannelIPs, 'VariableNames', ...
    %        compose('Ch %d IP', 1:app.NumChannels));
    %fpColumns = table(app.ChannelFPs, 'VariableNames', ...
    %        compose('Ch %d FP', 1:app.NumChannels));
    
    for i=1:app.NumChannels
        writetable( ...
            array2table(app.ChannelIPs(:,:,i)'), ...
            fullpath, 'Sheet', sprintf('Ch %u Int Prof', i), ...
            'WriteMode', 'overwritesheet', ...
            'WriteRowNames', false, ...
            'WriteVariableNames', false);
    end
    for i=1:app.NumChannels
        writetable(horzcat(indexColumns, ...
            array2table(app.ChannelFPs(:,:,i)')), ...
            fullpath, 'Sheet', sprintf('Ch %u Fit Curve', i), ...
            'WriteMode', 'overwritesheet', ...
            'WriteRowNames', false, ...
            'WriteVariableNames', false);
    end
%     writetable(horzcat(indexColumns, fpColumns), ...
%         fullpath, 'Sheet', 'Ch Fitted Curves', ...
%         'WriteMode', 'overwritesheet', ...
%         'WriteRowNames', false, ...
%         'WriteVariableNames', true);
end