function setupFPAxes(app)
% 1: Index, 2: Abs 3: Relative
% 4:(4+numch) = pkPos
% (4+numch+1):(4+1+2*numch) = pkHgt

%app.FPPlot = stackedplot(app.FP, ...
%    table('Size', [0 app.NumChannels*2+3], ...
%    'VariableTypes', cellstr( ...
%    ["uint64" "datetime" "duration" ...
%    "double" repelem("double",1,app.NumChannels) ...
%    repelem("uint8", 1, app.NumChannels)])), ...
%    {4:(4+app.NumChannels), ...
%    (4+app.NumChannels+1):(4+2*app.NumChannels+1)});

app.NRulers(2) = matlab.graphics.axis.decorator.NumericRuler(...
    "LimitsMode", "manual", "ExponentMode", "manual", ...
    "Exponent", 0, "Direction", "normal", ...
    "TickLabels", [], "TickLabelsMode", "manual", ...
    "MinorTick", "on", "MinorTickValuesMode", "manual");
app.NRulers(1) = matlab.graphics.axis.decorator.NumericRuler(...
    "LimitsMode", "manual", "ExponentMode", "manual", ...
    "Exponent", 0, "Direction", "normal", ...
    "MinorTick", "on", "MinorTickValuesMode", "manual", ...
    "TickValuesMode", "manual", "TickLabelsMode", "auto", ...
    "TickLabelInterpreter", "none", "TickLabels", [], ...
    "LimitsChangedFcn", @app.onXAxisLimitsChanged);

app.DRulers(2) = matlab.graphics.axis.decorator.DurationRuler(...
    "LimitsMode", "manual", "ExponentMode", "manual", ...
    "Exponent", 0, "Direction", "normal", "MinorTick", "on", ...
    "TickLabels", [], "MinorTickValuesMode", "manual");
app.DRulers(1) = matlab.graphics.axis.decorator.DurationRuler(...
    "LimitsMode", "manual", "ExponentMode", "manual", ...
    "Exponent", 0, "Direction", "normal", ...
    "MinorTick", "on", "MinorTickValuesMode", "manual", ...
    "TickValuesMode", "manual", "TickLabelsMode", "auto", ...
    "TickLabelInterpreter", "none", "TickLabels", [], ...
    "LimitsChangedFcn", @app.onXAxisLimitsChanged);

app.TRulers(2) = matlab.graphics.axis.decorator.DatetimeRuler(...
    "LimitsMode", "manual", "ExponentMode", "manual", ...
    "Exponent", 0, "Direction", "normal", "MinorTick", "on", ...
    "TickLabels", [], "MinorTickValuesMode", "manual");
app.TRulers(1) = matlab.graphics.axis.decorator.DatetimeRuler(...
    "LimitsMode", "manual", "ExponentMode", "manual", ...
    "Exponent", 0, "Direction", "normal", ...
    "MinorTick", "on", "MinorTickValuesMode", "manual", ...
    "TickValuesMode", "manual", "TickLabelsMode", "auto", ...
    "TickLabelInterpreter", "none", "TickLabels", [], ...
    "LimitsChangedFcn", @app.onXAxisLimitsChanged);

app.RulerLinks = [ ...
    linkprop(app.NRulers, {'Limits','Scale','MinorTick','TickValues','MinorTickValues'}), ... %,'TickValues','MinorTickValues'}), ...
    linkprop(app.DRulers, {'Limits','Scale','MinorTick','TickValues','MinorTickValues'}), .... %,'TickValues','MinorTickValues'}), ...
    linkprop(app.TRulers, {'Limits','Scale','MinorTick','TickValues','MinorTickValues'}) ... % ,'TickValues','MinorTickValues'}) ...
    ];

app.FPAxisLink = ...
    linkprop([app.PosAxes app.HgtAxes], ...
    {'XGrid', 'XMinorGrid', 'XTick', 'XMinorTick', ...
    'GridAlpha', 'GridColor', 'XColor', ...
    'GridLineStyle', 'Visible', 'MinorGridLineStyle', ...
    'MinorGridAlpha', 'MinorGridColor', ...
    ...'XScale'  ...
    });

% TODO: Set Clipping to 'on'?    
set(app.PosAxes, 'XAxis', app.NRulers(2), ...
    'YLimitMethod', 'tickaligned', ...
    'GridAlphaMode', 'manual', 'GridColorMode', 'manual', ...
    'XColorMode', 'manual', 'MinorGridAlphaMode', 'manual', ...
    'YColorMode', 'manual', 'YColor', [0 0 0], ...
    'MinorGridColorMode', 'manual', ...
    'CameraViewAngleMode', 'auto', ...
    'DataAspectRatioMode', 'auto', ...
    'PlotBoxAspectRatioMode', 'auto', ...
    'Color', [0.8 0.8 0.8], 'Tag', '2');
set(app.HgtAxes, 'XAxis', app.NRulers(1), ...
    'GridAlphaMode', 'manual', 'GridColorMode', 'manual', ...
    'XColorMode', 'manual', 'MinorGridAlphaMode', 'manual', ...
    'YColorMode', 'manual', 'Color', [0.8 0.8 0.8], ...
    'YLimitMethod', 'tickaligned', ...
    'CameraViewAngleMode', 'auto', ...
    'DataAspectRatioMode', 'auto', ...
    'PlotBoxAspectRatioMode', 'auto', 'Tag', '1');

yyaxis(app.HgtAxes, "right");
co = colororder(app.UIFigure);
app.eliPlotLine = matlab.graphics.primitive.Line( ...
    'Parent', app.HgtAxes, 'Color', co(end,:), ...
    'XDataMode', 'manual', 'YDataMode', 'manual', ...
    'XData', uint64.empty(), 'YData', double.empty());
app.HgtAxes.YColor = co(end,:);
yyaxis(app.HgtAxes, "left");

app.FPPagePatches = [ ...
    patch('Parent', app.HgtAxes, 'Tag', '1'), ...
    patch('Parent', app.PosAxes, 'Tag', '2') ];
set(app.FPPagePatches, 'FaceColor', [1 1 1], 'EdgeColor', 'none', ...
    'FaceAlpha', 1.0, 'EdgeAlpha', 0, 'AlphaDataMapping', 'none', ...
    'LineStyle', 'none', 'AlignVertexCenters', 'on', 'Marker', 'none', ...
    'PickableParts', 'visible', 'HitTest', 'off', 'Visible', false, ... %  true, ...
    'XData', [-1 -1 -1 -1], 'YData', [-1 -1 -1 -1]);
app.FPSelPatches = [ ...
    patch('Parent', app.HgtAxes, 'Tag', '1'), ...
    patch('Parent', app.PosAxes, 'Tag', '2') ];
set(app.FPSelPatches, 'FaceColor', [1 1 0], 'EdgeColor', 'none', ...
    'FaceAlpha', 0.28, 'EdgeAlpha', 0.95, 'AlphaDataMapping', 'none', ...
    'LineStyle', 'none', 'LineWidth', 0.1, 'LineJoin', 'round', ...
    'AlignVertexCenters', 'on', 'Marker', 'none', 'PickableParts', 'visible', ...
    'HitTest', 'on', 'Visible', false, 'XData', [0 0 0 0], 'YData', [0 0 0 0]);
set([app.HgtAxes.YAxis(1) ; app.PosAxes.YAxis], 'LimitsChangedFcn', ...
    @app.onYAxisLimitsChanged);

% app.FPRulers = [ ...
%     app.NRulers app.TRulers app.DRulers ...
% ];
app.FPRulers = { app.NRulers(1) app.NRulers(2) ...
    ; app.TRulers(1) app.TRulers(2) ...
    ; app.DRulers(1) app.DRulers(2) };
end