function setupROIs(app)
app.shadRects = [images.roi.Rectangle(app.PreviewAxes, ...
    "LineWidth", eps, ...
    "Deletable", false, "InteractionsAllowed", "none", ...
    "FaceSelectable", false, "FaceAlpha", 0.65, ...
    "LabelVisible", "off", "Rotatable", false, ...
    "Visible", false), ...
    images.roi.Rectangle(app.PreviewAxes, ...
    "LineWidth", eps, ...
    "Deletable", false, "InteractionsAllowed", "none", ...
    "FaceSelectable", false, "FaceAlpha", 0.65, ...
    "LabelVisible", "off", "Rotatable", false, ...
    "Visible", false) ...
    ];

app.highRect = images.roi.Rectangle(...
    "Color", "blue", "Deletable", false, ...
    "FaceAlpha", 0, "FaceSelectable", true, ...
    "LineWidth", eps, "MarkerSize", eps, ...
    "FixedAspectRatio", false, "InteractionsAllowed", "translate", ...
    "SelectedColor", "green", "LabelVisible", "off", ...
    "Rotatable", false, "RotationAngle", 0, ...
    "Parent", app.DataImageAxes, "Visible", false);

% TODO: When to change LabelVisible back to "hover"?
app.leftPSBLine = images.roi.Line( ...
    "Color", "blue", "InteractionsAllowed", "translate", ...
    "Deletable", false, "SelectedColor", "green", ...
    "LabelVisible", "on", "LabelAlpha", 0.7, ...
    "Label", "L", ...
    "Tag", '1', ...
    "Parent", app.DataImageAxes, "Visible", false);
app.leftPSBLine.LineWidth = 2\app.leftPSBLine.LineWidth;
app.PSBLeftSpinner.LowerLimitInclusive = "on";
app.PSBLeftSpinner.UpperLimitInclusive = "on";

app.rightPSBLine = images.roi.Line( ...
    "Color", "blue", "InteractionsAllowed", "translate", ...
    "Deletable", false, "SelectedColor", "green", ...
    "LabelVisible", "on", "LabelAlpha", 0.4, ...
    "Label", "R", ...
    "Tag", '2', "Visible", false, ...
    "Parent", app.DataImageAxes, ...
    "LineWidth", app.leftPSBLine.LineWidth);
app.PSBRightSpinner.LowerLimitInclusive = "on";
app.PSBRightSpinner.UpperLimitInclusive = "on";

app.botCropLine = images.roi.Line( ...
    "Color", "red", "InteractionsAllowed", "translate", ...
    "Deletable", false, "SelectedColor", "green", ...
    "LabelVisible", "on", "LabelAlpha", 0.4, ...
    "Label", "Bottom Crop Boundary", ... % NOTE: Need to swap these
    "Tag", ('1'), "Visible", false, ...
    "Parent", app.PreviewAxes);
app.MinYSpinner.LowerLimitInclusive = "on";
app.MinYSpinner.UpperLimitInclusive = "on";
app.botCropLine.MarkerSize = app.botCropLine.MarkerSize * 1.25;
app.botCropLine.LineWidth = 2\app.botCropLine.LineWidth;

app.topCropLine = images.roi.Line( ...
    "Color", "red", "InteractionsAllowed", "translate", ...
    "Deletable", false, "SelectedColor", "green", ...
    "LabelVisible", "on", "LabelAlpha", 0.7, ...
    "Label", "Top Crop Boundary", ...
    "Tag", ('2'), "Visible", false, ...
    "Parent", app.PreviewAxes, ...
    "LineWidth", app.botCropLine.LineWidth, ...
    "MarkerSize", app.botCropLine.MarkerSize);
app.MaxYSpinner.LowerLimitInclusive = "on";
app.MaxYSpinner.UpperLimitInclusive = "on";

app.CropLines = [ app.botCropLine app.topCropLine];
app.PSBLines = [ app.leftPSBLine app.rightPSBLine ];

for i=uint8(1:app.MaxMaxNumChs-1)
    % app.channelDivLines(i) = images.roi.Line(...
    %     "Color", "yellow", "Deletable", false, ...
    %     "InteractionsAllowed", "translate", ...
    %     "Visible", "off", ...
    %     "LabelVisible", "off", ...
    %     "Parent", app.PreviewAxes, 'Tag', char(i+48) ...
    %     );
    app.channelDivLines(i) = images.roi.Polygon( ...
        'Color', 'yellow', 'Deletable', false, ...
        'InteractionsAllowed', 'translate', ...
        'FaceAlpha', 1, 'MarkerSize', eps, ...
        'LineWidth', eps, 'LabelVisible', 'off', ...
        'Selected', false, 'Visible', 'off', ...
        'Parent', app.PreviewAxes, 'Tag', char(i+48));
    app.divLineListeners(i) = addlistener( ...
        app.channelDivLines(i), 'ROIMoved', ...
        @app.postmove_divline);
    app.divLineListeners2(i) = addlistener( ...
        app.channelDivLines(i), 'MovingROI', ...
        @app.postmove_divline);
    app.divLineListeners3(i) = addlistener( ...
        app.channelDivLines(i), 'ROIClicked', ...
        @app.postclick_divline);
end

% TODO: Also set to empty on (re)init
app.ChanDivLines = images.roi.Polygon.empty(); %images.roi.Line.empty();

%             app.rectListener = [ addlistener(app.highRect, ...
%                 'ROIMoved', @app.postmove_rect), ...
%                 addlistener(app.highRect, ...
%                 'MovingROI', @app.postmove_rect) ];
%             app.leftLineListener = [ addlistener(app.leftPSBLine, ...
%                 'MovingROI', @app.postmove_PSBline), ...
%                 addlistener(app.leftPSBLine, ...
%                 'ROIMoved', @app.postmove_PSBline) ];
%             app.rightLineListener = [ addlistener(app.rightPSBLine, ...
%                 'ROIMoved', @app.postmove_PSBline), ...
%                 addlistener(app.rightPSBLine, ...
%                 'MovingROI', @app.postmove_PSBline) ];
app.topLineListener = [ addlistener(app.topCropLine, ...
    'ROIMoved', @app.postmove_cropline), ...
    addlistener(app.topCropLine, ...
    'MovingROI', @app.postmove_cropline) ];
app.botLineListener = [ addlistener(app.botCropLine, ...
    'ROIMoved', @app.postmove_cropline), ...
    addlistener(app.botCropLine, ...
    'MovingROI', @app.postmove_cropline)];

app.leftLineListener = [ addlistener(app.leftPSBLine, ...
    'ROIMoved', @app.postmove_PSBline), ...
    addlistener(app.leftPSBLine, ...
    'MovingROI', @app.postmove_PSBline) ];
app.rightLineListener = [ addlistener(app.rightPSBLine, ...
    'ROIMoved', @app.postmove_PSBline), ...
    addlistener(app.rightPSBLine, ...
    'MovingROI', @app.postmove_PSBline) ];

app.roiClickListener = [...
    addlistener( ...
    app.leftPSBLine, 'ROIClicked', @app.postclick_PSBline), ...
    addlistener( ...
    app.rightPSBLine, 'ROIClicked', @app.postclick_PSBline), ...
    addlistener( ...
    app.highRect, 'ROIClicked', @app.postclick_PSBroi), ...
    addlistener( ...
    app.topCropLine, 'ROIClicked', @app.postclick_cropline), ...
    addlistener( ...
    app.botCropLine, 'ROIClicked', @app.postclick_cropline)
    ];
end