function setupIPAxis(app, ax, i)
    ax.Tag = char(i+48);
    % ax.NextPlot = 'replacechildren';
    ax.ContextMenu = app.PlotContextMenu;
    hold(ax, "off"); 
    ax.Toolbar.Visible = false;
    disableDefaultInteractivity(ax); % TODO
    ax.BusyAction = 'cancel';
    ax.ButtonDownFcn = @app.onIProfClicked;
    
    persistent co;
    if isempty(co)
        co = colororder(app.UIFigure);
    end

    app.IPpatches(i) = matlab.graphics.primitive.Patch('Parent', ax, ...
        'HitTest', 'off', 'PickableParts', 'none', ...
        'FaceAlpha', 1, 'LineStyle', 'none', 'FaceColor', [1 1 1], 'Visible', true);

    % hold(ax, "on");
    

    

    % app.IPfitLines(i) = matlab.graphics.primitive.Line('Parent', ax, ...
    %     'YData', NaN(1, app.fdm(2), 'double'), ...
    %     'XData', (1:app.fdm(2)), ...
    %     'Visible', true, 'Color', [0 0 0 ], ...
    %     'DisplayName', 'Fitted Curve');

    app.IPpeakLines(i) = matlab.graphics.chart.decoration.ConstantLine( ...
        'Parent', ax, 'Value', NaN(1,1,'double'), 'Color', 'red', 'InterceptAxis', 'x', ...
        'LineWidth', 0.5, 'Visible', true, 'HitTest', 'off', 'PickableParts', 'none');

    color1 = co(i,:);
    color2 = min(color1 + 1.5*(1-max(color1)), 1);
    color3 = max(color1 - 1.5*min(color1), 0);


    % [0.8 0.4 0.6]
    % [0.9 0.6 0.2]

    color1c = 1 - co(i,:);
    color2c = min(color1c + 1.5*(1-max(color1c)), 1);
    color3c = max(color1c - 1.5*min(color1c), 0);
    
    app.IPzoneRects(2, i) = patch(ax, ...
        'LineStyle', 'none', 'FaceColor', color2c, 'FaceAlpha', 0.4, ...
        'Visible', false, 'HitTest', 'off', 'PickableParts', 'none', ...
        'UserData', vertcat(color1c, color2c, color3c));

    app.IPdataLines(i) = matlab.graphics.primitive.Line('Parent', ax, ...
        'YData', NaN(1, app.fdm(2), 'double'), ...
        'XData', (1:app.fdm(2)), 'HitTest', 'off', ...
        'Visible', true, 'MarkerEdgeColor', color1, ...
        'Color', color2, 'UserData', vertcat(color1, color2, color3), ...
        'LineWidth', 0.01, 'LineStyle', 'none', ...
        'Marker', '.', 'MarkerSize', 4, ...
        'DisplayName', 'Intensity Profile');
    
    app.IPfitLines(i) = matlab.graphics.chart.primitive.Area('Parent', ax, ...
        'YData', NaN(1, app.fdm(2), 'double'), ...
        'XData', 1:app.fdm(2), 'Visible', true, ...
        'EdgeColor', [0 0 0], 'LineStyle', 'none', ...
        'FaceColor', [0 0 0], ...
        'LineWidth', 0.75, 'FaceAlpha', 0.4, ...
        'FaceColorMode', 'manual', 'HitTest', 'off', ...
        'PickableParts', 'none', 'DisplayName', 'Fitted Curve');

    % app.IPzoneRects(1,i) = images.roi.Rectangle('Parent', ax, ...
    %     'Visible', true, 'Color', [0.8 0.8 0.8], ...
    %     'LineWidth', eps, 'FaceAlpha', 0.8, ...
    %     "Deletable", true, "InteractionsAllowed", "translate", ...
    %     "FaceSelectable", true, "LabelVisible", "off", "Rotatable", false, ...
    %     'Tag', char(i+48));

    % hold(ax, "off");
    ax.Color = [1 1 1];
end


