function outArgs = updateTicksA(timeZero, isRuler, pixelWidth, lims, ...
    axisModeIndex, zoomModeOn, resUnit, assumeChanged, varargin)
if isRuler
    zoomModeOn = logical.empty();
end
if ~isscalar(resUnit)
    resUnit = resUnit{axisModeIndex, 1};
end
[ minTicks, showMinTicks, minTicksChanged, majTicksChanged, ...
    majTicks, majLabels, majTickInfo ] = generateTicks( ...
    timeZero, axisModeIndex, zoomModeOn, ...
    pixelWidth, lims, resUnit, assumeChanged, varargin{:});
% fprintf('[updateTicksA] (%d) Length of generated minor/major ticks: %d / %d\n', ...
%    isRuler, length(minTicks), length(majTicks));

outArgs = { minTicks, showMinTicks, minTicksChanged, majTicksChanged, ...
    majTicks, majLabels, majTickInfo };
end